---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex:arm64v8-latest 
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /media/USBHDD3/00_AppData/plex/config:/config
      - /media/USBHDD1:/USBHDD1
      - /media/USBHDD2:/USBHDD2
      - /media/USBHDD3:/USBHDD3
    restart: unless-stopped
