services:
  codeserver:
    image: lscr.io/linuxserver/code-server
    container_name: codeserver
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - PASSWORD= #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=$SUDO_PASSWORD #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - URL_BASE=/codeserver
    volumes:
      - /media/USBHDD3/00_AppData/codeserver/config:/config
      - /media/USBHDD1:/USBHDD1
      - /media/USBHDD2:/USBHDD2
      - /media/USBHDD3:/USBHDD3
    ports:
      - 4848:8443
    restart: unless-stopped
