services:
  firefox:
    image: jlesage/firefox
    ports:
      - 5800:5800
    environment:
      - URL_BASE=/firefox
    volumes:
      - /media/USBHDD3/00_AppData/firefox/config:/config
      - /media/USBHDD1:/USBHDD1
      - /media/USBHDD2:/USBHDD2
      - /media/USBHDD3:/USBHDD3
