services:
  kavita:
    image: lscr.io/linuxserver/kavita
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /media/USBHDD3/00_AppData/kavita/config:/config
      - /media/USBHDD3/05_eBooks/02_eBooks:/books
      - /media/USBHDD1:/USBHDD1
      - /media/USBHDD2:/USBHDD2
      - /media/USBHDD3:/USBHDD3
    ports:
      - 5000:5000
    restart: unless-stopped
