services:
  wetty:
    image: wettyoss/wetty
    container_name: wetty
    restart: unless-stopped
    ports:
      - "3030:3000"
    environment:
      - SSHHOST=$HOST #192.168...
      - SSHPORT=$PORT
      - SSHUSER=$USER
      - BASE=/
    volumes:
      - /media/USBHDD3/00_AppData/wetty/config/wetty_key:/root/.ssh/id_rsa:ro  
